### ISSUE TITLE
Improve test coverage!

### ISSUE THREAD

**Issue by sminez** [sminez/arpy#1]
Test coverage currently sits at 45%...we can do better.

- [ ] Overall test coverage reaches at least 80%
  - [x] ar_types
  - [ ] [Concepts](https://github.com/sminez/concepts) submodule has its own test suite
  - [x] Visualisation and lex/parse
  - [x] Operators
  - [x] Differentials

**Comment by sminez** [comment]
From looking at [coveralls](https://coveralls.io/github/sminez/arpy) it looks like only del_grouping.py is currently above 80%.

**Comment by deggenschwiler** [comment]
I have no idea what I'm doing but it's a good place to start! Thanks Innes!

**Comment by sminez** [comment]
Woohoo! Here's a few tips.

1. Run this command before starting:
```
git checkout -b dev/<new-branch-name>

# For example:
git checkout -b dev/deggens-tests
```
That will create a new branch for you to work on so that you can commit to your heart's content without worrying about breaking anything :) [This bit is VERY important! If multiple people push to master then we can stomp on each other's work :( )

2. Try to keep individual commits to small logical changes (completing a single test case for example)
Open test_operations.py in the tests directory (I've stubbed out some test cases for you) and fill in one of the test cases. If you follow the example of the other tests these ones should be quite simple: Make the objects you need (`Alpha`, `Pair`, `MultiVector` etc) one to call the function on and one that represents the correct answer. Call the function and then use the `assert` keyword to verify that the the two are equal.
```assert thing_1 == thing_2```

3. Save and move to the root of the repo where you can run `sudo python3 setup.py test` to run the full test suite: If everything is green, you win! If not it should tell you what went wrong and you can go fix it :)

4. Once things are passing you need to commit and push the changes:
```
git commit -a -m"<short description of what you did>"

# First time only on a branch you will need to do this:
git push --set-upstream origin dev/<your-branch-name>

# after that you just need...
git push
```
You should see a short summary of the changes that have been pushed. You can then go [here](https://github.com/sminez/arpy/branches) to find you branch and create a pull request! (I'll let you figure that bit out ;) )

5. (Optional) If you want to see how the coverage has changed, go [here](https://travis-ci.org/sminez/arpy) to see if the test run has finished and then [here](https://coveralls.io/github/sminez/arpy) to see the coverage report.
